In [13]:
from amuse.units import units
import numpy as np
import matplotlib.pyplot as plt
from amuse.units import nbody_system
from amuse.units import constants
from amuse.lab import Particles

In [2]:
def drag_force (k, m, M, A, r, alpha):
    #change in orbital velocity
    dv_dt = -9*k*constants.G*m*(A**5)*np.sin(2*alpha)/(4*(r**7))
    
    #energy dissipation
    dE_dt = -9*k*G**(3/2)*M**(1/2)*m**2*A**5*np.sin(2*alpha)/(2*r**(15/2))

In [48]:
class TidalForce ():
    def __init__(self):
        pass
    
    def add_particles(self, particle_set):
        self.particles = particle_set
    
    def tidal_acceleration(self, k, alpha):
        A = 4*np.pi*np.square(((1|units.RJupiter).value_in(units.m)))
        M = (1|units.MJupiter).value_in(units.kg)
        G = constants.G.value_in((units.m)**3/(units.kg*units.s**2))
        
        r = np.sqrt(np.sum(np.square(self.particles.position - self.particles[1].position),axis=1))
        
        abs_vel = np.sqrt(np.sum(np.square(self.particles.velocity),axis=1))
        
        abs_acc = np.zeros(len(self.particles))
        mask = np.arange(len(self.particles)) != 1
        abs_acc[mask] = -9*k*G*self.particles.mass[mask]*(A**5)*np.sin(2*alpha)/(4*r[mask]**7)
                
        ax = abs_acc*(self.particles.vx/abs_vel)
        ay = abs_acc*(self.particles.vy/abs_vel)
        az = abs_acc*(self.particles.vz/abs_vel)
        return ax, ay, az
    
    def get_gravity_at_point(self, eps, x, y, z):
        #k from literature, alpha guess
        return self.tidal_acceleration(k=0.565, alpha=0.1)

In [49]:
test = Particles(2)
test[0].position = (1,2,3)
test[0].velocity = (1,1,1)
test[0].mass = 1
test[1].mass = 2
test[1].position = (10,11,12)
test[1].velocity = (2,3,2)

In [50]:
test_hydro_code = TidalForce()
test_hydro_code.add_particles(test)
test_hydro_code.get_gravity_at_point(0,0,0,0)

(array([ -4.75562300e+64,   0.00000000e+00]),
 array([ -4.75562300e+64,   0.00000000e+00]),
 array([ -4.75562300e+64,   0.00000000e+00]))